import os

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory


def generate_launch_description():
    return LaunchDescription(
        [
            DeclareLaunchArgument("source_mode", default_value="fixed"),
            DeclareLaunchArgument(
                "fixed_capsule_file",
                default_value=os.path.join(
                    get_package_share_directory("openarmx_nvblox_bringup"),
                    "config",
                    "fixed_cable_capsules.yaml",
                ),
            ),
            DeclareLaunchArgument("depth_topic", default_value="/perception/cable_depth"),
            DeclareLaunchArgument("camera_info_topic", default_value="/perception/cable_depth/camera_info"),
            DeclareLaunchArgument("pointcloud_topic", default_value="/nvblox_node/static_esdf_pointcloud"),
            DeclareLaunchArgument("mesh_topic", default_value="/nvblox_node/mesh"),
            DeclareLaunchArgument("voxel_layer_topic", default_value="/nvblox_node/color_layer"),
            DeclareLaunchArgument("voxel_centers_are_global", default_value="true"),
            DeclareLaunchArgument("marker_topic", default_value="/perception/cable_capsules"),
            DeclareLaunchArgument("radius_m", default_value="0.02"),
            DeclareLaunchArgument("alpha", default_value="0.45"),
            DeclareLaunchArgument("color_r", default_value="0.2"),
            DeclareLaunchArgument("color_g", default_value="0.55"),
            DeclareLaunchArgument("color_b", default_value="1.0"),
            DeclareLaunchArgument("min_line_length_px", default_value="70"),
            DeclareLaunchArgument("max_line_gap_px", default_value="45"),
            DeclareLaunchArgument("hough_threshold", default_value="18"),
            DeclareLaunchArgument("sample_band_px", default_value="5"),
            DeclareLaunchArgument("min_points_per_capsule", default_value="20"),
            DeclareLaunchArgument("min_capsule_length_m", default_value="0.08"),
            DeclareLaunchArgument("max_capsules", default_value="8"),
            DeclareLaunchArgument("publish_rate_hz", default_value="10.0"),
            DeclareLaunchArgument("point_voxel_size_m", default_value="0.015"),
            DeclareLaunchArgument("mesh_vertices_are_global", default_value="true"),
            DeclareLaunchArgument("mesh_direct_fit_enabled", default_value="true"),
            DeclareLaunchArgument("mesh_cluster_voxel_size_m", default_value="0.03"),
            DeclareLaunchArgument("mesh_cluster_neighbor_voxels", default_value="2"),
            DeclareLaunchArgument("mesh_cluster_min_points", default_value="10"),
            DeclareLaunchArgument("mesh_cluster_min_length_m", default_value="0.12"),
            DeclareLaunchArgument("mesh_cluster_max_radius_m", default_value="0.10"),
            DeclareLaunchArgument("mesh_cluster_endpoint_percentile", default_value="0.0"),
            DeclareLaunchArgument("component_fit_enabled", default_value="true"),
            DeclareLaunchArgument("component_min_points", default_value="6"),
            DeclareLaunchArgument("component_min_length_m", default_value="0.03"),
            DeclareLaunchArgument("component_max_radius_m", default_value="0.055"),
            DeclareLaunchArgument("component_neighbor_voxels", default_value="1"),
            DeclareLaunchArgument("component_merge_enabled", default_value="true"),
            DeclareLaunchArgument("component_merge_gap_m", default_value="0.18"),
            DeclareLaunchArgument("component_merge_perp_m", default_value="0.045"),
            DeclareLaunchArgument("component_merge_direction_dot", default_value="0.90"),
            DeclareLaunchArgument("capsule_ema_alpha", default_value="0.18"),
            DeclareLaunchArgument("capsule_hold_cycles", default_value="8"),
            DeclareLaunchArgument("freeze_capsules", default_value="true"),
            DeclareLaunchArgument("freeze_min_capsules", default_value="2"),
            DeclareLaunchArgument("freeze_delay_s", default_value="5.0"),
            DeclareLaunchArgument("freeze_stable_cycles", default_value="15"),
            DeclareLaunchArgument("freeze_stability_tolerance_m", default_value="0.01"),
            DeclareLaunchArgument("left_capsule_z_offset", default_value="0.0"),
            DeclareLaunchArgument("right_capsule_z_offset", default_value="0.0"),
            DeclareLaunchArgument("ransac_fallback_enabled", default_value="false"),
            DeclareLaunchArgument("ransac_iterations", default_value="180"),
            DeclareLaunchArgument("ransac_inlier_distance_m", default_value="0.035"),
            DeclareLaunchArgument("ransac_min_inliers", default_value="25"),
            DeclareLaunchArgument("ransac_remove_distance_m", default_value="0.055"),
            Node(
                package="openarmx_nvblox_bringup",
                executable="cable_capsule_marker_node.py",
                name="cable_capsule_marker",
                output="screen",
                parameters=[
                    {
                        "source_mode": LaunchConfiguration("source_mode"),
                        "fixed_capsule_file": LaunchConfiguration("fixed_capsule_file"),
                        "depth_topic": LaunchConfiguration("depth_topic"),
                        "camera_info_topic": LaunchConfiguration("camera_info_topic"),
                        "pointcloud_topic": LaunchConfiguration("pointcloud_topic"),
                        "mesh_topic": LaunchConfiguration("mesh_topic"),
                        "voxel_layer_topic": LaunchConfiguration("voxel_layer_topic"),
                        "voxel_centers_are_global": LaunchConfiguration("voxel_centers_are_global"),
                        "marker_topic": LaunchConfiguration("marker_topic"),
                        "radius_m": LaunchConfiguration("radius_m"),
                        "alpha": LaunchConfiguration("alpha"),
                        "color_r": LaunchConfiguration("color_r"),
                        "color_g": LaunchConfiguration("color_g"),
                        "color_b": LaunchConfiguration("color_b"),
                        "min_line_length_px": LaunchConfiguration("min_line_length_px"),
                        "max_line_gap_px": LaunchConfiguration("max_line_gap_px"),
                        "hough_threshold": LaunchConfiguration("hough_threshold"),
                        "sample_band_px": LaunchConfiguration("sample_band_px"),
                        "min_points_per_capsule": LaunchConfiguration("min_points_per_capsule"),
                        "min_capsule_length_m": LaunchConfiguration("min_capsule_length_m"),
                        "max_capsules": LaunchConfiguration("max_capsules"),
                        "publish_rate_hz": LaunchConfiguration("publish_rate_hz"),
                        "point_voxel_size_m": LaunchConfiguration("point_voxel_size_m"),
                        "mesh_vertices_are_global": LaunchConfiguration("mesh_vertices_are_global"),
                        "mesh_direct_fit_enabled": LaunchConfiguration("mesh_direct_fit_enabled"),
                        "mesh_cluster_voxel_size_m": LaunchConfiguration("mesh_cluster_voxel_size_m"),
                        "mesh_cluster_neighbor_voxels": LaunchConfiguration("mesh_cluster_neighbor_voxels"),
                        "mesh_cluster_min_points": LaunchConfiguration("mesh_cluster_min_points"),
                        "mesh_cluster_min_length_m": LaunchConfiguration("mesh_cluster_min_length_m"),
                        "mesh_cluster_max_radius_m": LaunchConfiguration("mesh_cluster_max_radius_m"),
                        "mesh_cluster_endpoint_percentile": LaunchConfiguration("mesh_cluster_endpoint_percentile"),
                        "component_fit_enabled": LaunchConfiguration("component_fit_enabled"),
                        "component_min_points": LaunchConfiguration("component_min_points"),
                        "component_min_length_m": LaunchConfiguration("component_min_length_m"),
                        "component_max_radius_m": LaunchConfiguration("component_max_radius_m"),
                        "component_neighbor_voxels": LaunchConfiguration("component_neighbor_voxels"),
                        "component_merge_enabled": LaunchConfiguration("component_merge_enabled"),
                        "component_merge_gap_m": LaunchConfiguration("component_merge_gap_m"),
                        "component_merge_perp_m": LaunchConfiguration("component_merge_perp_m"),
                        "component_merge_direction_dot": LaunchConfiguration("component_merge_direction_dot"),
                        "capsule_ema_alpha": LaunchConfiguration("capsule_ema_alpha"),
                        "capsule_hold_cycles": LaunchConfiguration("capsule_hold_cycles"),
                        "freeze_capsules": LaunchConfiguration("freeze_capsules"),
                        "freeze_min_capsules": LaunchConfiguration("freeze_min_capsules"),
                        "freeze_delay_s": LaunchConfiguration("freeze_delay_s"),
                        "freeze_stable_cycles": LaunchConfiguration("freeze_stable_cycles"),
                        "freeze_stability_tolerance_m": LaunchConfiguration("freeze_stability_tolerance_m"),
                        "left_capsule_z_offset": LaunchConfiguration("left_capsule_z_offset"),
                        "right_capsule_z_offset": LaunchConfiguration("right_capsule_z_offset"),
                        "ransac_fallback_enabled": LaunchConfiguration("ransac_fallback_enabled"),
                        "ransac_iterations": LaunchConfiguration("ransac_iterations"),
                        "ransac_inlier_distance_m": LaunchConfiguration("ransac_inlier_distance_m"),
                        "ransac_min_inliers": LaunchConfiguration("ransac_min_inliers"),
                        "ransac_remove_distance_m": LaunchConfiguration("ransac_remove_distance_m"),
                    }
                ],
            ),
        ]
    )
