<?xml version="1.0"?>
<package format="3">
  <name>openarmx_nvblox_bringup</name>
  <version>0.0.1</version>
  <description>Launch and configuration files for nvblox with OpenArmX perception inputs.</description>
  <maintainer email="wanghua@example.com">wanghua</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>nvblox_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>nvblox_ros</exec_depend>
  <exec_depend>nvblox_examples_bringup</exec_depend>
  <exec_depend>openarmx_visual_cues</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
